# Generated by Django 4.1.7 on 2023-03-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_information", "0005_auto_20220302_1457"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="code",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="middlename",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="salary",
        ),
    ]
